services:
  wolfott-notification-service:
    image: maven:latest  # Use the latest Maven image
    working_dir: /app
    volumes:
      - ./notification-service:/app  # Mount the notification-service directory
    command: mvn spring-boot:run
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - wolfott-network

networks:
  wolfott-network:
    external: true
