spring:
    application:
        name: auth-service
    config:
        import: optional:configserver:http://localhost:9000

#eureka:
#    instance:
#        prefer-ip-address: true
#        hostname: localhost
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka
#        register-with-eureka: true
#        fetch-registry: true