services:
  wolfott-line-service:
    image: maven:latest  # Use the latest Maven image
    working_dir: /app
    volumes:
      - ./line-service:/app  # Mount the line-service directory
    command: mvn spring-boot:run
    environment:
      - SPRING_APPLICATION_NAME=line-service
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - wolfott-network

networks:
  wolfott-network:
    external: true
