services:
  wolfott-config-server:
    image: maven:latest  # Use the latest Maven image
    working_dir: /app
    volumes:
      - ./config-server:/app  # Mount the config-server directory
    command: mvn spring-boot:run
    environment:
      - SPRING_APPLICATION_NAME=config-server
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - wolfott-network

networks:
  wolfott-network:
    external: true
