services:
  wolfott-server-service:
    image: maven:latest  # Use the latest Maven image
    working_dir: /app
    volumes:
      - ./server-service:/app  # Mount the server-service directory
    command: mvn spring-boot:run
    environment:
      - SPRING_APPLICATION_NAME=server-service
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - wolfott-network

networks:
  wolfott-network:
    external: true
