services:
  wolfott-epg-service:
    image: maven:latest  # Use the latest Maven image
    working_dir: /app
    volumes:
      - ./epg-service:/app  # Mount the epg-service directory
    command: mvn spring-boot:run
    environment:
      - SPRING_APPLICATION_NAME=epg-service
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - wolfott-network

networks:
  wolfott-network:
    external: true
