services:
  wolfott-user-service:
    image: maven:latest  # Use the latest Maven image
    working_dir: /app
    volumes:
      - ./user-service:/app  # Mount the user-service directory
    command: mvn spring-boot:run
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - wolfott-network

networks:
  wolfott-network:
    external: true
