services:
  wolfott-gateway-service:
    image: maven:latest  # Use the latest Maven image
    working_dir: /app
    volumes:
      - ./gateway-service:/app  # Mount the gateway-service directory
    command: mvn spring-boot:run
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - wolfott-network

networks:
  wolfott-network:
    external: true
