package com.wolfott.mangement.line.requests;

import java.sql.Timestamp;

public record LineUpdateRequest(
        Long id,
        Long memberId,
        String username,
        String password,
        String lastIp,
        Long expDate,
        Integer adminEnabled,
        Integer enabled,
        String adminNotes,
        String resellerNotes,
        String bouquet,
        String allowedOutputs,
        Integer maxConnections,
        Boolean isRestreamer,
        Boolean isTrial,
        Boolean isMag,
        Boolean isE2,
        Boolean isStalker,
        Boolean isIsplock,
        String allowedIps,
        String allowedUa,
        Long createdAt,
        Long pairId,
        Integer forceServerId,
        String asNumber,
        String ispDesc,
        String forcedCountry,
        Boolean bypassUa,
        String playToken,
        Long lastExpirationVideo,
        Long packageId,
        String accessToken,
        String contact,
        Long lastActivity,
        String lastActivityArray,
        Timestamp updated) {}